INSERT INTO logro (id_logro, nombre, descripcion, experiencia) VALUES ("coment_1", "Primer comentario",  "Escribe tu primer comentario", 0);
INSERT INTO logro (id_logro, nombre, descripcion, experiencia) VALUES ("coment_10", "10 comentarios", "Escribe 10 comentarios", 0);
INSERT INTO logro (id_logro, nombre, descripcion, experiencia) VALUES ("coment_100", "100 comentarios", "Escribe 100 comentarios", 0);
INSERT INTO logro (id_logro, nombre, descripcion, experiencia) VALUES ("coment_2000", "2kmentarios", "Escribe 2000 comentarios", 0);
INSERT INTO logro (id_logro, nombre, descripcion, experiencia) VALUES ("vot_1", "Primera votacion", "Vota tu primer comentario", 0);
INSERT INTO logro (id_logro, nombre, descripcion, experiencia) VALUES ("vot_100", "100 votaciones", "Vota 100 comentarios", 0);
INSERT INTO logro (id_logro, nombre, descripcion, experiencia) VALUES ("vot_1000", "1000 votaciones", "Vota 1000 comentarios", 0);
INSERT INTO logro (id_logro, nombre, descripcion, experiencia) VALUES ("se_vot_1", "Primer voto", "Alguien ha votado por primera vez una de tus publicaciones", 0);
INSERT INTO logro (id_logro, nombre, descripcion, experiencia) VALUES ("se_vot_100", "100 votos", "Han votado tus publicaciones 100 veces", 0);
INSERT INTO logro (id_logro, nombre, descripcion, experiencia) VALUES ("se_vot_1000", "1000 votos", "Han votado tus publicaciones 1000 veces", 0);
INSERT INTO logro (id_logro, nombre, descripcion, experiencia) VALUES ("esc_pos", "Escalando posiciones", "Tu publicación ha llegado a 100 votos", 0);
INSERT INTO logro (id_logro, nombre, descripcion, experiencia) VALUES ("cima", "En la cima", "Tu publicacion ha llegado a 1000 votos", 0);
INSERT INTO logro (id_logro, nombre, descripcion, experiencia) VALUES ("hacks", "Hacks!!!", "Tus publicaciones han sido reportadas 100 veces", 0);
INSERT INTO logro (id_logro, nombre, descripcion, experiencia) VALUES ("pri_pas", "Primeros pasos", "Añade tu primer juego a la lista de pendientes", 0);
INSERT INTO logro (id_logro, nombre, descripcion, experiencia) VALUES ("ni_ma", "El niño se hace mayor", "Añade tu primer juego a la lista de enCurso", 0);
INSERT INTO logro (id_logro, nombre, descripcion, experiencia) VALUES ("to_ju", "Todo un jugón", "Completa tu primer juego", 0);
INSERT INTO logro (id_logro, nombre, descripcion, experiencia) VALUES ("bu_pla", "Buen planificador", "Ten al menos 10 juegos en tu lista de pendientes", 0);
INSERT INTO logro (id_logro, nombre, descripcion, experiencia) VALUES ("fa_tie", "¿Falta tiempo?", "Ten al menos 50 juegos en tu lista de pendientes", 0);
INSERT INTO logro (id_logro, nombre, descripcion, experiencia) VALUES ("ni_2_vi", "Ni en 2 vidas", "Ten al menos 100 juegos en tu lista de pendientes", 0);
INSERT INTO logro (id_logro, nombre, descripcion, experiencia) VALUES ("no_bu_id", "No es buena idea...", "Ten al menos 5 juegos en tu lista enCurso", 0);
INSERT INTO logro (id_logro, nombre, descripcion, experiencia) VALUES ("car_extr", "(o_O)", "Ten al menos 50 juegos en tu lista de enCurso", 0);
INSERT INTO logro (id_logro, nombre, descripcion, experiencia) VALUES ("xp_mi", "Experiencia a mi", "Completa al menos 5 juegos", 0);
INSERT INTO logro (id_logro, nombre, descripcion, experiencia) VALUES ("ex_nb", "Exnoob", "Completa al menos 25 juegos", 0);
INSERT INTO logro (id_logro, nombre, descripcion, experiencia) VALUES ("god_on", "God mode ON", "Completa al menos 75 juegos", 0);
INSERT INTO logro (id_logro, nombre, descripcion, experiencia) VALUES ("sal_call", "Sal a la calle", "Completa al menos 150 juegos", 0);
INSERT INTO logro (id_logro, nombre, descripcion, experiencia) VALUES ("1_silla", "Eres uno con la silla", "Completa al menos 250 juegos", 0);
INSERT INTO logro (id_logro, nombre, descripcion, experiencia) VALUES ("subxsub", "Sub x Sub", "Ten la misma cantidad de seguidos que de seguidores (mas de 50)", 0);
INSERT INTO logro (id_logro, nombre, descripcion, experiencia) VALUES ("ec_ojo", "Echando el ojo", "Sigue a tu primer usuario", 0);
INSERT INTO logro (id_logro, nombre, descripcion, experiencia) VALUES ("cu_mar", "Curso de marujeo", "Sigue a 50 usuarios", 0);
INSERT INTO logro (id_logro, nombre, descripcion, experiencia) VALUES ("gra_mar", "Graduado en marujeo", "Sigue a 100 usuarios", 0);
INSERT INTO logro (id_logro, nombre, descripcion, experiencia) VALUES ("todo_oye", "El que todo lo oye", "Sigue a 1000 usuarios", 0);
INSERT INTO logro (id_logro, nombre, descripcion, experiencia) VALUES ("er_pop", "Eres popular", "Te sigue al menos 1 persona", 0);
INSERT INTO logro (id_logro, nombre, descripcion, experiencia) VALUES ("te_me_mo", "Tell me more", "Te siguen al menos 100 personas", 0);
INSERT INTO logro (id_logro, nombre, descripcion, experiencia) VALUES ("boein_747", "Llenando un Boeing 747", "Te siguen al menos 500 personas", 0);
INSERT INTO logro (id_logro, nombre, descripcion, experiencia) VALUES ("eje_fans", "Ejercito de fans", "Te siguen al menos 1000 personas", 0);
INSERT INTO logro (id_logro, nombre, descripcion, experiencia, secreto) VALUES ("gr_escal", "La gran escalada", "Se el usuario con mayor crecimiento del mes", 0, 1);
INSERT INTO logro (id_logro, nombre, descripcion, experiencia, secreto) VALUES ("el_fav", "El favorito", "Se el usuario con la publicacion más votada del mes", 0, 1);

